### ISSUE TITLE
关于图片背景渐变幻灯片

### ISSUE THREAD

**Issue by Qifcn** [HeskeyBaozi/hexo-theme-lite#29]
第一次提问题有点紧张啊。
这个功能需要怎么实现，有点小白不懂啊

**Comment by HeskeyBaozi** [comment]
?
背景使用渐变色背景：https://github.com/HeskeyBaozi/hexo-theme-lite#features
你说的“幻灯片”能具体说一下是什么吗？

**Comment by Qifcn** [comment]
你好作者，你可以看一下我的博客qifcn.com
不知道这个是否可以，就是在一个固定的时间换一下背景图片

**Comment by Qifcn** [comment]
还有就是可不可以一直单栏下去，不是看完了一页像这个博客一样https://maicong.me实现预加载下一页。翻页建议

**Comment by HeskeyBaozi** [comment]
了解到了你的需求
1. 不同时间段的背景图片可以定制
2. 加载更多 （自动加载更多）

第一个我觉得挺酷的，会加在todo列表中。第二个一直加载更多我觉得更多的个人习惯的问题，而且加载数量上来了对主页性能有较大影响。本身config的分页数量这些设置就已经满足需求了。

感谢建议。
