### ISSUE TITLE
手机访问样式优化问题

### ISSUE THREAD

**Issue by bentoule** [HeskeyBaozi/hexo-theme-lite#30]
> 手机访问时，带图片的文章，首页展示的时候中间或有一大部分空白

IOS UC和自带浏览器是这样的，这个阔以优化下吗

**Comment by HeskeyBaozi** [comment]
可以截图看一下是什么问题吗？
目前`webkit`内核的浏览器都是正常的

**Comment by bentoule** [comment]
![](http://bendan.vip/imgs/2018/01/fankui.jpg)


哈哈，截图如上

**Comment by HeskeyBaozi** [comment]
https://github.com/HeskeyBaozi/hexo-theme-lite/releases/tag/v1.4.0
在`v1.4.0`版本中已修复

修复移动端走马灯露白问题 1de42fb244dac252ca5e65914a3f171ed8306b7f #32 

[如何升级主题](https://github.com/HeskeyBaozi/hexo-theme-lite#how-to-upgrade-this-theme--%E5%A6%82%E4%BD%95%E5%8D%87%E7%BA%A7%E4%B8%BB%E9%A2%98)
