### ISSUE TITLE
_config.yml root设置内容无法获取静态资源

### ISSUE THREAD

**Issue by japperhu** [HeskeyBaozi/hexo-theme-lite#34]
hi,觉得您的hexo lite主题不错，试用了一下，发现如果_config.yml 的root选项设置内容，就无法获取静态资源了，提示404，应该是url中缺少root导致的

**Comment by HeskeyBaozi** [comment]
默认的网站根目录root设置为`/`
也就是说，网站通常是`https://heskeybaozi.github.io/#/`类似这样访问的。

如果您的网站存放在子目录中，例如 `http://yoursite.com/blog/#/`这样访问。则需要编译一次主题。
同时也不要在根__config.yml下设置root字段即可。

做法也很简单。

1. 进入主题目录 themes/lite。
2. 在主题目录下打开终端执行`npm install`或者`yarn`来安装依赖，速度取决于网速
3. 找到主题目录下 config/index.js这个文件（也就是[这个文件](https://github.com/HeskeyBaozi/hexo-theme-lite/blob/master/config/index.js#L70)），将第70行左右的

```
assetsPublicPath: '/'
```

这个路径修改成你需要的路径。
4. 在主题目录下打开终端执行`npm run build`编译主题
5. 在返回到博客目录，打开终端执行`hexo generate`。之后再部署即可

还有问题的话，直接在这里留言即可

**Comment by FaustYKKN** [comment]
要是把  scripts\generate-api.js:16:44 的 function filterHTMLTags 返回值由 `null` 改为 `String()` ，可以直接写空博客，但是会不会出 bug 呢?
很棒的主题呦，大赞~
