### ISSUE TITLE
How to get those fancy images in the post list

### ISSUE THREAD

**Issue by bergziege** [HeskeyBaozi/hexo-theme-lite#41]
Hi,

in your blog and in the screenshot to this theme there is a image shown between post title and content. When clicked, he image opens in a lightbox.

How to get this effect?

Would be nice, if you could include it to the documentation as it adds a lot to the theme.

Thanks,
bergziege

**Comment by HeskeyBaozi** [comment]
add `<!-- more -->` in your raw markdown post before the image that you want to display. It will automatically fetch  the **first** image to show in the homepage as an excerpt.

for example:
[https://heskeybaozi.github.io/#/posts/merry-christmas](https://heskeybaozi.github.io/#/posts/merry-christmas)

the raw markdown post:
```md
---
title: Merry Christmas 🎅
date: 2017-12-24 20:08:50
tags:
---

## 🎅又是一年圣诞时

希望每一个度过平安夜的人可以被这个世界善待 💖

<!-- more -->

![show-love](/assets/show-love.jpg)
```

preview:
![111](https://user-images.githubusercontent.com/15819224/39488442-e4970d12-4db4-11e8-9a65-795234375869.png)

**Comment by bergziege** [comment]
Thanks a lot!

**Comment by fightwithtiger** [comment]
作者你好，这个截断我放在图片前不起作用是怎么回事？还有就是分页是怎么配置的呢
