### ISSUE TITLE
审核URL问题：how to add url to power-by elem at footer?

### ISSUE THREAD

**Issue by radaren** [HeskeyBaozi/hexo-theme-lite#42]
您好，我需要补充域名备案后的审核，我想用power-by来实现，请问如何添加URL。
vue的语法不太熟悉。。

hello, i want to know how to add url in vue to this theme, as normal hexo added by footer.ejs, which i tried but not works.

**Comment by HeskeyBaozi** [comment]
该问题已在`v1.4.1`版本中解决，可以将powered-by设置为链接。[查看版本ChangeLog](https://github.com/HeskeyBaozi/hexo-theme-lite/releases/tag/v1.4.1)

- 如何查看主题版本？
主题文件夹下[package.json](https://github.com/HeskeyBaozi/hexo-theme-lite/blob/master/package.json#L3)文件中的`version`字段
