### ISSUE TITLE
功能支持问题 unsupport problems

### ISSUE THREAD

**Issue by radaren** [HeskeyBaozi/hexo-theme-lite#43]
修改过程中发现:
不支持修改目录栏的icon,
不支持hexo-math,hexo-render-mathjax两种插件

- not support for change other menu_icons(lite/_config.yml) in http://fontawesome.io/icons/
- not support for hexo-math and hexo-renderer-mathjax

**Comment by HeskeyBaozi** [comment]
- 顶部菜单栏图表修改是支持的
https://github.com/HeskeyBaozi/hexo-theme-lite/blob/master/_config.yml#L44
请认真阅读文档和配置
- 关于数学符号的显示
准确的说，这个主题并没有干涉markdown文件渲染，你需要按照[他的说明](https://github.com/phoenixcw/hexo-renderer-mathjax/blob/master/lib/mathjax.html)来在`layout/index.ejs`引入
```html
<script type="text/x-mathjax-config">
    MathJax.Hub.Config({
        tex2jax: {
            inlineMath: [ ["$","$"], ["\\(","\\)"] ],
            skipTags: ['script', 'noscript', 'style', 'textarea', 'pre', 'code'],
            processEscapes: true
        }
    });
    MathJax.Hub.Queue(function() {
        var all = MathJax.Hub.getAllJax();
        for (var i = 0; i < all.length; ++i)
            all[i].SourceElement().parentNode.className += ' has-jax';
    });
</script>
<script src="https://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML"></script>
```
其他样式文件也要自己在合适地方（例如`<head>`）中引入

**Comment by HeskeyBaozi** [comment]
公式的需求也挺常见的，之后应该也会直接支持，就不用再install插件了。

**Comment by HeskeyBaozi** [comment]
还有要在博客根目录下的`_config.yml`中添加
```yml
plugins:
- hexo-renderer-mathjax
```

**Comment by radaren** [comment]
我尝试更换为fa-chess-knight没有渲染出来0.0

**Comment by radaren** [comment]
公式可以了!多谢~
不知道这个主题可不可以做一些vue的二次开发..我尝试更改.vue和改.ts的参数没有被hexo g 渲染到,我看了一下结构目录是生成了混淆过的.css,.js之类代码来渲染的..想请教repo主是用什么工具生成的

**Comment by HeskeyBaozi** [comment]
修改完后你得执行[构建](https://github.com/HeskeyBaozi/hexo-theme-lite/blob/master/package.json#L9)命令才能生效呀
进入主题文件夹
```sh
npm install # 安装依赖
npm run build # 构建
```
