### ISSUE TITLE
Archives 显示不全

### ISSUE THREAD

**Issue by radaren** [HeskeyBaozi/hexo-theme-lite#44]
有两篇文章时候随机显示一篇。。。
没有按照title部分的`date: 2018-05-04`来控制

**Comment by HeskeyBaozi** [comment]
没看懂。问题怎么复现？怎么出现的？

**Comment by radaren** [comment]
就是如果我把首页显示的pages设置为1之后，再archive里面的page也是1了。。
我想可不可以archive里面的分页数目和首页不同

**Comment by HeskeyBaozi** [comment]
https://github.com/HeskeyBaozi/hexo-theme-lite/blob/master/scripts/generate-api.js#L200
