### ISSUE TITLE
很棒的主题，发现一个小问题。

### ISSUE THREAD

**Issue by ghost** [HeskeyBaozi/hexo-theme-lite#48]
当有多个pages时：
    点击一个pages=>加载后点击另一个pages：
        1、地址栏链接不会改变。
        2、gitment评论不会重新加载。
        3、如果这时再点击第一次点击的pages，出现加载进度条但不会切换pages页面。

**Comment by HeskeyBaozi** [comment]
我曾经也出现过这种情况，后来我发现是我的网络问题，部分页面的代码懒加载结果没有下载下来。按`F12`中`network`发现还在加载。
