### ISSUE TITLE
i cannot install gitment for my harrykhang.com

### ISSUE THREAD

**Issue by ghost** [HeskeyBaozi/hexo-theme-lite#50]
can you help me to install gitment ?
my blog repo is holalatiger.github.io

**Comment by ghost** [comment]
i reall dont know how to do step 3 : https://github.com/aimingoo/gitmint

**Comment by HeskeyBaozi** [comment]
just create an oauth app in github.
https://github.com/HeskeyBaozi/hexo-theme-lite#cool-features

![image](https://user-images.githubusercontent.com/15819224/44626454-403c3c00-a94f-11e8-9755-23ab8975c15b.png)
