### ISSUE TITLE
Code Display Only In One Line

### ISSUE THREAD

**Issue by jskyzero** [HeskeyBaozi/hexo-theme-lite#8]
1. initial file list bellow

    [3-1_image_dithering.txt](https://github.com/HeskeyBaozi/hexo-theme-lite/files/1567833/3-1_image_dithering.txt)

2. want comment system and google analysis system.

**Comment by HeskeyBaozi** [comment]
# Hexo Configuration
## Docs: http://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
title: Hello, Lite
subtitle: this is subtitle
description: This is description
author: HeskeyBaozi
language:
timezone:

# URL
## If your site is put in a subdirectory, set url as 'http://yoursite.com/child' and root as '/child/'
url: http://yoursite.com
root: /
permalink: :year/:month/:day/:title/
permalink_defaults:

# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render:

# Writing
new_post_name: :title.md # File name of new posts
default_layout: post
titlecase: false # Transform title into titlecase
external_link: true # Open external links in new tab
filename_case: 0
render_drafts: false
post_asset_folder: false
relative_link: false
future: true
highlight:
  enable: true
  line_number: true
  auto_detect: true
  tab_replace:

# Category & Tag
default_category: uncategorized
category_map:
tag_map:

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD
time_format: HH:mm:ss

# Pagination
## Set per_page to 0 to disable pagination
per_page: 10
pagination_dir: page

# Extensions
## Plugins: http://hexo.io/plugins/
## Themes: http://hexo.io/themes/
theme: lite

# Deployment
## Docs: http://hexo.io/docs/deployment.html
deploy:
  type:

**Comment by HeskeyBaozi** [comment]
[_config.txt](https://github.com/HeskeyBaozi/hexo-theme-lite/files/1567867/_config.txt)

**Comment by jskyzero** [comment]
就很绝望，发现这是个概率事件？？有时候就会是好的，如果不行就clean 然后再试试说不定就可以，很绝望。我已经迁移[过来了](https://jskyzero.github.io/#/)
